### PR TITLE
Test pr

### PR DESCRIPTION
**Pull request by Morl99**

### CODE REVIEW

**Comment by Morl99** [comment]
[//]: # (semantic-release-github-pr 455305e52592e90ab7b3899803109a9f921a6ab5 excote v1.0.0)
Merging this PR will publish the following release:

# 1.0.0 (2020-10-29)


### Features

* Initial release with semantic release ([ce717bc](https://github.com/dbsystel/excote/commit/ce717bcc639d7a73bee3e590cd7357088e882843))

**Comment by Morl99** [comment]
[//]: # (semantic-release-github-pr 455305e52592e90ab7b3899803109a9f921a6ab5 excote v1.0.0)
Merging this PR will publish the following release:

# 1.0.0 (2020-10-29)


### Features

* Initial release with semantic release ([ce717bc](https://github.com/dbsystel/excote/commit/ce717bcc639d7a73bee3e590cd7357088e882843))

**Comment by Morl99** [comment]
[//]: # (semantic-release-github-pr 4a0805f0d317171fb12e3a4daa3845db7e19e522 excote v1.0.0)
Merging this PR will publish the following release:

# 1.0.0 (2020-10-29)


### Features

* Initial release with semantic release ([ce717bc](https://github.com/dbsystel/excote/commit/ce717bcc639d7a73bee3e590cd7357088e882843))

**Review by steffakasid — APPROVED** [review]

**Comment by Morl99** [comment]
We close this PR, it was just meant to demonstrate the Preview PR Comment feature of the workflow.

**Pull request closed without merging**
